server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://cms-discovery.herokuapp.com/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: CMS-Api-Gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://perera-tuition-class.herokuapp.com"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

      routes:
        - id: CMS-Student-Service
          uri: https://cms-student.herokuapp.com
          predicates:
            - Path=/api/v1/student/**
        - id: CMS-Class-Location
          uri: https://cms-tuition-class.herokuapp.com
          predicates:
            - Path=/api/v1/tuition/**
        - id: CMS-Student-Payment
          uri: https://cms-payment.herokuapp.com
          predicates:
            - Path=/api/v1/payment/**
        - id: CMS-Auth-Service
          uri: https://cms-auth-service.herokuapp.com
          predicates:
            - Path=/user/**

