server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: CMS-Api-Gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: CMS-Student-Service
          uri: http://localhost:8104
          predicates:
            - Path=/student/**
        - id: CMS-Class-Location
          uri: http://localhost:8105
          predicates:
            - Path=/tuition/**
        - id: CMS-Student-Payment
          uri: http://localhost:8101
          predicates:
            - Path=/payment/**
        - id: CMS-Auth-Service
          uri: http://localhost:8111
          predicates:
            - Path=/user/**

